[2024-07-12T05:06:45.124+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T05:06:45.143+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_ipl_zip_to_s3.stream_to_s3 manual__2024-07-12T05:06:44.104044+00:00 [queued]>
[2024-07-12T05:06:45.150+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_ipl_zip_to_s3.stream_to_s3 manual__2024-07-12T05:06:44.104044+00:00 [queued]>
[2024-07-12T05:06:45.151+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-12T05:06:45.166+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stream_to_s3> on 2024-07-12 05:06:44.104044+00:00
[2024-07-12T05:06:45.171+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T05:06:45.172+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-07-12T05:06:45.172+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_ipl_zip_to_s3', 'stream_to_s3', 'manual__2024-07-12T05:06:44.104044+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/download_upload.py', '--cfg-path', '/tmp/tmp3abqhieo']
[2024-07-12T05:06:45.173+0000] {standard_task_runner.py:91} INFO - Job 140: Subtask stream_to_s3
[2024-07-12T05:06:45.719+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_ipl_zip_to_s3.stream_to_s3 manual__2024-07-12T05:06:44.104044+00:00 [running]> on host 318b387ee83d
[2024-07-12T05:06:45.786+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_ipl_zip_to_s3' AIRFLOW_CTX_TASK_ID='stream_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T05:06:44.104044+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T05:06:44.104044+00:00'
[2024-07-12T05:06:45.787+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T05:06:45.805+0000] {base_aws.py:587} WARNING - Unable to find AWS Connection ID 'aws_credentials', switching to empty.
[2024-07-12T05:06:45.806+0000] {base_aws.py:164} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2024-07-12T05:06:47.196+0000] {download_upload.py:42} ERROR - Failed to stream file to S3: Unable to locate credentials
[2024-07-12T05:06:47.197+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T05:06:47.197+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/download_upload.py", line 39, in stream_to_s3
    s3_client.upload_fileobj(response.raw, bucket_name, s3_key)
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/s3/inject.py", line 642, in upload_fileobj
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/s3transfer/upload.py", line 764, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1001, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1027, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/signers.py", line 199, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2024-07-12T05:06:47.205+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_ipl_zip_to_s3, task_id=stream_to_s3, run_id=manual__2024-07-12T05:06:44.104044+00:00, execution_date=20240712T050644, start_date=20240712T050645, end_date=20240712T050647
[2024-07-12T05:06:47.215+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 140 for task stream_to_s3 (Unable to locate credentials; 71)
[2024-07-12T05:06:47.232+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T05:06:47.243+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T05:06:47.245+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
