[2024-07-12T05:54:55.892+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T05:54:55.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_ipl_zip_to_s3.invoke_lambda_unzip manual__2024-07-12T05:49:47.944199+00:00 [queued]>
[2024-07-12T05:54:55.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_ipl_zip_to_s3.invoke_lambda_unzip manual__2024-07-12T05:49:47.944199+00:00 [queued]>
[2024-07-12T05:54:55.914+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-12T05:54:55.928+0000] {taskinstance.py:2330} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_unzip> on 2024-07-12 05:49:47.944199+00:00
[2024-07-12T05:54:55.935+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=722) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T05:54:55.936+0000] {standard_task_runner.py:63} INFO - Started process 723 to run task
[2024-07-12T05:54:55.936+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_ipl_zip_to_s3', 'invoke_lambda_unzip', 'manual__2024-07-12T05:49:47.944199+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/stream_upload_to_s3.py', '--cfg-path', '/tmp/tmpofts3lhe']
[2024-07-12T05:54:55.938+0000] {standard_task_runner.py:91} INFO - Job 148: Subtask invoke_lambda_unzip
[2024-07-12T05:54:55.973+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_ipl_zip_to_s3.invoke_lambda_unzip manual__2024-07-12T05:49:47.944199+00:00 [running]> on host 318b387ee83d
[2024-07-12T05:54:56.058+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_ipl_zip_to_s3' AIRFLOW_CTX_TASK_ID='invoke_lambda_unzip' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T05:49:47.944199+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T05:49:47.944199+00:00'
[2024-07-12T05:54:56.059+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T05:54:56.069+0000] {lambda_function.py:217} INFO - Invoking AWS Lambda function: lambda_handler with payload: {'s3_key': 'None'}
[2024-07-12T05:54:56.076+0000] {base.py:84} INFO - Using connection ID 's3-bucket-conn' for task execution.
[2024-07-12T05:54:56.077+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3-bucket-conn', conn_type='aws') credentials retrieved from login and password.
[2024-07-12T05:54:56.276+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T05:54:56.277+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 218, in execute
    response = self.hook.invoke_lambda(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/lambda_function.py", line 83, in invoke_lambda
    return self.conn.invoke(**trim_none_values(invoke_args))
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 724, in conn
    return self.get_client_type(region_name=self.region_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 694, in get_client_type
    return session.client(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 924, in create_client
    region_name = self._resolve_region_name(region_name, config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 1023, in _resolve_region_name
    validate_region_name(region_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/utils.py", line 1320, in validate_region_name
    raise InvalidRegionError(region_name=region_name)
botocore.exceptions.InvalidRegionError: Provided region_name 'US East (Ohio) us-east-2' doesn't match a supported format.
[2024-07-12T05:54:56.285+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=upload_ipl_zip_to_s3, task_id=invoke_lambda_unzip, run_id=manual__2024-07-12T05:49:47.944199+00:00, execution_date=20240712T054947, start_date=20240712T055455, end_date=20240712T055456
[2024-07-12T05:54:56.294+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 148 for task invoke_lambda_unzip (Provided region_name 'US East (Ohio) us-east-2' doesn't match a supported format.; 723)
[2024-07-12T05:54:56.310+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T05:54:56.324+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T05:54:56.325+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
