[2024-07-12T05:49:54.267+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T05:49:54.281+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_ipl_zip_to_s3.invoke_lambda_unzip manual__2024-07-12T05:49:47.944199+00:00 [queued]>
[2024-07-12T05:49:54.290+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_ipl_zip_to_s3.invoke_lambda_unzip manual__2024-07-12T05:49:47.944199+00:00 [queued]>
[2024-07-12T05:49:54.291+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-12T05:49:54.302+0000] {taskinstance.py:2330} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_unzip> on 2024-07-12 05:49:47.944199+00:00
[2024-07-12T05:49:54.307+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=651) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T05:49:54.308+0000] {standard_task_runner.py:63} INFO - Started process 652 to run task
[2024-07-12T05:49:54.308+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_ipl_zip_to_s3', 'invoke_lambda_unzip', 'manual__2024-07-12T05:49:47.944199+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/stream_upload_to_s3.py', '--cfg-path', '/tmp/tmpuixgolk4']
[2024-07-12T05:49:54.309+0000] {standard_task_runner.py:91} INFO - Job 145: Subtask invoke_lambda_unzip
[2024-07-12T05:49:54.342+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_ipl_zip_to_s3.invoke_lambda_unzip manual__2024-07-12T05:49:47.944199+00:00 [running]> on host 318b387ee83d
[2024-07-12T05:49:54.455+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_ipl_zip_to_s3' AIRFLOW_CTX_TASK_ID='invoke_lambda_unzip' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T05:49:47.944199+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T05:49:47.944199+00:00'
[2024-07-12T05:49:54.456+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T05:49:54.467+0000] {lambda_function.py:217} INFO - Invoking AWS Lambda function: lambda_handler with payload: {'s3_key': 'None'}
[2024-07-12T05:49:54.473+0000] {base_aws.py:587} WARNING - Unable to find AWS Connection ID 'aws_credentials', switching to empty.
[2024-07-12T05:49:54.474+0000] {base_aws.py:164} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2024-07-12T05:49:54.726+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T05:49:54.726+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 218, in execute
    response = self.hook.invoke_lambda(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/lambda_function.py", line 83, in invoke_lambda
    return self.conn.invoke(**trim_none_values(invoke_args))
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 724, in conn
    return self.get_client_type(region_name=self.region_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 694, in get_client_type
    return session.client(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 520, in _get_client_args
    return args_creator.get_client_args(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/args.py", line 100, in get_client_args
    final_args = self.compute_client_args(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/args.py", line 219, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/args.py", line 369, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/args.py", line 474, in _resolve_endpoint
    return endpoint_bridge.resolve(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 625, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/regions.py", line 229, in construct_endpoint
    result = self._endpoint_for_partition(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/regions.py", line 277, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
[2024-07-12T05:49:54.734+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_ipl_zip_to_s3, task_id=invoke_lambda_unzip, run_id=manual__2024-07-12T05:49:47.944199+00:00, execution_date=20240712T054947, start_date=20240712T054954, end_date=20240712T054954
[2024-07-12T05:49:54.743+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 145 for task invoke_lambda_unzip (You must specify a region.; 652)
[2024-07-12T05:49:54.762+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T05:49:54.775+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T05:49:54.777+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
