[2024-07-16T07:18:56.164+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T07:18:56.191+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: glue_crawler_etl_pipeline.start_glue_job manual__2024-07-16T07:09:02.837883+00:00 [queued]>
[2024-07-16T07:18:56.203+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: glue_crawler_etl_pipeline.start_glue_job manual__2024-07-16T07:09:02.837883+00:00 [queued]>
[2024-07-16T07:18:56.204+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-16T07:18:56.218+0000] {taskinstance.py:2330} INFO - Executing <Task(GlueJobOperator): start_glue_job> on 2024-07-16 07:09:02.837883+00:00
[2024-07-16T07:18:56.222+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2461) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-16T07:18:56.224+0000] {standard_task_runner.py:63} INFO - Started process 2462 to run task
[2024-07-16T07:18:56.224+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'glue_crawler_etl_pipeline', 'start_glue_job', 'manual__2024-07-16T07:09:02.837883+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/etl_populate_database.py', '--cfg-path', '/tmp/tmpdpufu4gr']
[2024-07-16T07:18:56.225+0000] {standard_task_runner.py:91} INFO - Job 280: Subtask start_glue_job
[2024-07-16T07:18:56.270+0000] {task_command.py:426} INFO - Running <TaskInstance: glue_crawler_etl_pipeline.start_glue_job manual__2024-07-16T07:09:02.837883+00:00 [running]> on host 0ec6e6e2bd09
[2024-07-16T07:18:56.356+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='glue_crawler_etl_pipeline' AIRFLOW_CTX_TASK_ID='start_glue_job' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T07:09:02.837883+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T07:09:02.837883+00:00'
[2024-07-16T07:18:56.358+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T07:18:56.372+0000] {glue.py:186} INFO - Initializing AWS Glue Job: etl_s3_to_redshift. Wait for completion: True
[2024-07-16T07:18:56.373+0000] {glue.py:365} INFO - Checking if job already exists: etl_s3_to_redshift
[2024-07-16T07:18:56.383+0000] {base.py:84} INFO - Using connection ID 's3-bucket-conn' for task execution.
[2024-07-16T07:18:56.384+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3-bucket-conn', conn_type='aws') credentials retrieved from login and password.
[2024-07-16T07:18:57.175+0000] {glue.py:207} INFO - You can monitor this Glue Job run at: https://console.aws.amazon.com/gluestudio/home?region=us-east-2#/job/etl_s3_to_redshift/run/jr_fc44dd142ad1881219f4d851ebe7afa97aa268b9ef4efb7c92099b1e954bc8a9
[2024-07-16T07:18:57.267+0000] {glue.py:348} INFO - Polling for AWS Glue Job etl_s3_to_redshift current run state with status RUNNING
[2024-07-16T07:19:03.360+0000] {glue.py:348} INFO - Polling for AWS Glue Job etl_s3_to_redshift current run state with status RUNNING
[2024-07-16T07:19:09.440+0000] {glue.py:348} INFO - Polling for AWS Glue Job etl_s3_to_redshift current run state with status RUNNING
[2024-07-16T07:19:15.523+0000] {glue.py:348} INFO - Polling for AWS Glue Job etl_s3_to_redshift current run state with status RUNNING
[2024-07-16T07:19:21.614+0000] {glue.py:348} INFO - Polling for AWS Glue Job etl_s3_to_redshift current run state with status RUNNING
[2024-07-16T07:19:27.701+0000] {glue.py:348} INFO - Polling for AWS Glue Job etl_s3_to_redshift current run state with status RUNNING
[2024-07-16T07:19:33.787+0000] {glue.py:348} INFO - Polling for AWS Glue Job etl_s3_to_redshift current run state with status RUNNING
[2024-07-16T07:19:39.870+0000] {glue.py:348} INFO - Polling for AWS Glue Job etl_s3_to_redshift current run state with status RUNNING
[2024-07-16T07:19:45.963+0000] {glue.py:348} INFO - Polling for AWS Glue Job etl_s3_to_redshift current run state with status RUNNING
[2024-07-16T07:19:52.044+0000] {glue.py:345} INFO - Exiting Job jr_fc44dd142ad1881219f4d851ebe7afa97aa268b9ef4efb7c92099b1e954bc8a9 Run State: FAILED
[2024-07-16T07:19:52.045+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T07:19:52.052+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 221, in execute
    glue_job_run = self.glue_job_hook.job_completion(self.job_name, self._job_run_id, self.verbose)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 297, in job_completion
    ret = self._handle_state(job_run_state, job_name, run_id, verbose, next_log_tokens)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 346, in _handle_state
    raise AirflowException(job_error_message)
airflow.exceptions.AirflowException: Exiting Job jr_fc44dd142ad1881219f4d851ebe7afa97aa268b9ef4efb7c92099b1e954bc8a9 Run State: FAILED
[2024-07-16T07:19:52.055+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=glue_crawler_etl_pipeline, task_id=start_glue_job, run_id=manual__2024-07-16T07:09:02.837883+00:00, execution_date=20240716T070902, start_date=20240716T071856, end_date=20240716T071952
[2024-07-16T07:19:52.066+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-07-16T07:19:52.067+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-07-16T07:19:52.067+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-07-16T07:19:52.073+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-07-16T07:19:52.073+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-07-16T07:19:52.074+0000] {taskinstance.py:879} ERROR - Failed to send email to: ['your_email@example.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2676, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2701, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 221, in execute
    glue_job_run = self.glue_job_hook.job_completion(self.job_name, self._job_run_id, self.verbose)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 297, in job_completion
    ret = self._handle_state(job_run_state, job_name, run_id, verbose, next_log_tokens)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 346, in _handle_state
    raise AirflowException(job_error_message)
airflow.exceptions.AirflowException: Exiting Job jr_fc44dd142ad1881219f4d851ebe7afa97aa268b9ef4efb7c92099b1e954bc8a9 Run State: FAILED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1063, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 877, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3163, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1065, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-07-16T07:19:52.087+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 280 for task start_glue_job (Exiting Job jr_fc44dd142ad1881219f4d851ebe7afa97aa268b9ef4efb7c92099b1e954bc8a9 Run State: FAILED; 2462)
[2024-07-16T07:19:52.095+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T07:19:52.114+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T07:19:52.118+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
