[2024-07-12T22:00:33.141+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T22:00:33.162+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_and_invoke_lambda.invoke_lambda_unzip manual__2024-07-12T22:00:27.044160+00:00 [queued]>
[2024-07-12T22:00:33.174+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_and_invoke_lambda.invoke_lambda_unzip manual__2024-07-12T22:00:27.044160+00:00 [queued]>
[2024-07-12T22:00:33.174+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-12T22:00:33.189+0000] {taskinstance.py:2330} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_unzip> on 2024-07-12 22:00:27.044160+00:00
[2024-07-12T22:00:33.193+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1839) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T22:00:33.194+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_and_invoke_lambda', 'invoke_lambda_unzip', 'manual__2024-07-12T22:00:27.044160+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/stream_upload_to_s3.py', '--cfg-path', '/tmp/tmplvqzq8de']
[2024-07-12T22:00:33.195+0000] {standard_task_runner.py:63} INFO - Started process 1840 to run task
[2024-07-12T22:00:33.195+0000] {standard_task_runner.py:91} INFO - Job 225: Subtask invoke_lambda_unzip
[2024-07-12T22:00:33.243+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_and_invoke_lambda.invoke_lambda_unzip manual__2024-07-12T22:00:27.044160+00:00 [running]> on host e900ffca6a6f
[2024-07-12T22:00:33.365+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_and_invoke_lambda' AIRFLOW_CTX_TASK_ID='invoke_lambda_unzip' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T22:00:27.044160+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T22:00:27.044160+00:00'
[2024-07-12T22:00:33.366+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T22:00:33.383+0000] {lambda_function.py:217} INFO - Invoking AWS Lambda function: ***-lamda-unzip with payload: {"s3_key": "ipl_matches.zip"}
[2024-07-12T22:00:33.391+0000] {base.py:84} INFO - Using connection ID 's3-bucket-conn' for task execution.
[2024-07-12T22:00:33.392+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3-bucket-conn', conn_type='aws') credentials retrieved from login and password.
[2024-07-12T22:00:36.980+0000] {lambda_function.py:226} INFO - Lambda response metadata: {'RequestId': '182f1528-c156-4771-b41b-51fed6fbbb72', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Fri, 12 Jul 2024 22:00:38 GMT', 'content-type': 'application/json', 'content-length': '114', 'connection': 'keep-alive', 'x-amzn-requestid': '182f1528-c156-4771-b41b-51fed6fbbb72', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-6691a783-1887a1c071dc53012ebd23c7;parent=02fd474170cd6bd0;sampled=0;lineage=101f7269:0'}, 'RetryAttempts': 0}
[2024-07-12T22:00:36.981+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T22:00:36.982+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 246, in execute
    raise ValueError(
ValueError: ('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': '182f1528-c156-4771-b41b-51fed6fbbb72', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Fri, 12 Jul 2024 22:00:38 GMT', 'content-type': 'application/json', 'content-length': '114', 'connection': 'keep-alive', 'x-amzn-requestid': '182f1528-c156-4771-b41b-51fed6fbbb72', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-6691a783-1887a1c071dc53012ebd23c7;parent=02fd474170cd6bd0;sampled=0;lineage=101f7269:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage":"2024-07-12T22:00:38.244Z 182f1528-c156-4771-b41b-51fed6fbbb72 Task timed out after 3.01 seconds"}'})
[2024-07-12T22:00:36.990+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_and_invoke_lambda, task_id=invoke_lambda_unzip, run_id=manual__2024-07-12T22:00:27.044160+00:00, execution_date=20240712T220027, start_date=20240712T220033, end_date=20240712T220036
[2024-07-12T22:00:37.007+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 225 for task invoke_lambda_unzip (('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': '182f1528-c156-4771-b41b-51fed6fbbb72', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Fri, 12 Jul 2024 22:00:38 GMT', 'content-type': 'application/json', 'content-length': '114', 'connection': 'keep-alive', 'x-amzn-requestid': '182f1528-c156-4771-b41b-51fed6fbbb72', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-6691a783-1887a1c071dc53012ebd23c7;parent=02fd474170cd6bd0;sampled=0;lineage=101f7269:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage":"2024-07-12T22:00:38.244Z 182f1528-c156-4771-b41b-51fed6fbbb72 Task timed out after 3.01 seconds"}'}); 1840)
[2024-07-12T22:00:37.027+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T22:00:37.042+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T22:00:37.043+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
