[2024-07-12T22:02:52.646+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T22:02:52.661+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_and_invoke_lambda.invoke_lambda_unzip manual__2024-07-12T22:02:45.537691+00:00 [queued]>
[2024-07-12T22:02:52.668+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_and_invoke_lambda.invoke_lambda_unzip manual__2024-07-12T22:02:45.537691+00:00 [queued]>
[2024-07-12T22:02:52.669+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-12T22:02:52.682+0000] {taskinstance.py:2330} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_unzip> on 2024-07-12 22:02:45.537691+00:00
[2024-07-12T22:02:52.686+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1879) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T22:02:52.688+0000] {standard_task_runner.py:63} INFO - Started process 1880 to run task
[2024-07-12T22:02:52.688+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_and_invoke_lambda', 'invoke_lambda_unzip', 'manual__2024-07-12T22:02:45.537691+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/stream_upload_to_s3.py', '--cfg-path', '/tmp/tmp4hl43rjd']
[2024-07-12T22:02:52.689+0000] {standard_task_runner.py:91} INFO - Job 230: Subtask invoke_lambda_unzip
[2024-07-12T22:02:52.729+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_and_invoke_lambda.invoke_lambda_unzip manual__2024-07-12T22:02:45.537691+00:00 [running]> on host e900ffca6a6f
[2024-07-12T22:02:52.816+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_and_invoke_lambda' AIRFLOW_CTX_TASK_ID='invoke_lambda_unzip' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T22:02:45.537691+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T22:02:45.537691+00:00'
[2024-07-12T22:02:52.817+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T22:02:52.829+0000] {lambda_function.py:217} INFO - Invoking AWS Lambda function: ***-lamda-unzip with payload: {"s3_key": "ipl_matches.zip"}
[2024-07-12T22:02:52.837+0000] {base.py:84} INFO - Using connection ID 's3-bucket-conn' for task execution.
[2024-07-12T22:02:52.838+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3-bucket-conn', conn_type='aws') credentials retrieved from login and password.
[2024-07-12T22:02:56.376+0000] {lambda_function.py:226} INFO - Lambda response metadata: {'RequestId': 'cd9b2c1f-520b-4c5d-b6fd-fe97c08d0209', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Fri, 12 Jul 2024 22:02:57 GMT', 'content-type': 'application/json', 'content-length': '114', 'connection': 'keep-alive', 'x-amzn-requestid': 'cd9b2c1f-520b-4c5d-b6fd-fe97c08d0209', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-6691a80e-58bb1b494b6d5d8759925259;parent=0c868b887a05b6e6;sampled=0;lineage=101f7269:0'}, 'RetryAttempts': 0}
[2024-07-12T22:02:56.377+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T22:02:56.377+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 246, in execute
    raise ValueError(
ValueError: ('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': 'cd9b2c1f-520b-4c5d-b6fd-fe97c08d0209', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Fri, 12 Jul 2024 22:02:57 GMT', 'content-type': 'application/json', 'content-length': '114', 'connection': 'keep-alive', 'x-amzn-requestid': 'cd9b2c1f-520b-4c5d-b6fd-fe97c08d0209', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-6691a80e-58bb1b494b6d5d8759925259;parent=0c868b887a05b6e6;sampled=0;lineage=101f7269:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage":"2024-07-12T22:02:57.650Z cd9b2c1f-520b-4c5d-b6fd-fe97c08d0209 Task timed out after 3.03 seconds"}'})
[2024-07-12T22:02:56.385+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_and_invoke_lambda, task_id=invoke_lambda_unzip, run_id=manual__2024-07-12T22:02:45.537691+00:00, execution_date=20240712T220245, start_date=20240712T220252, end_date=20240712T220256
[2024-07-12T22:02:56.406+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 230 for task invoke_lambda_unzip (('Lambda function execution resulted in error', {'ResponseMetadata': {'RequestId': 'cd9b2c1f-520b-4c5d-b6fd-fe97c08d0209', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Fri, 12 Jul 2024 22:02:57 GMT', 'content-type': 'application/json', 'content-length': '114', 'connection': 'keep-alive', 'x-amzn-requestid': 'cd9b2c1f-520b-4c5d-b6fd-fe97c08d0209', 'x-amz-function-error': 'Unhandled', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-6691a80e-58bb1b494b6d5d8759925259;parent=0c868b887a05b6e6;sampled=0;lineage=101f7269:0'}, 'RetryAttempts': 0}, 'Payload': '{"errorMessage":"2024-07-12T22:02:57.650Z cd9b2c1f-520b-4c5d-b6fd-fe97c08d0209 Task timed out after 3.03 seconds"}'}); 1880)
[2024-07-12T22:02:56.439+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T22:02:56.454+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T22:02:56.457+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
