[2024-07-12T03:52:24.287+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T03:52:24.302+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_and_upload_to_s3.download_file scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T03:52:24.312+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_and_upload_to_s3.download_file scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T03:52:24.313+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-12T03:52:24.329+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_file> on 2024-07-11 00:00:00+00:00
[2024-07-12T03:52:24.334+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=512) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T03:52:24.336+0000] {standard_task_runner.py:63} INFO - Started process 513 to run task
[2024-07-12T03:52:24.336+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'download_and_upload_to_s3', 'download_file', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/download_extract_dag.py', '--cfg-path', '/tmp/tmpj7zgebne']
[2024-07-12T03:52:24.337+0000] {standard_task_runner.py:91} INFO - Job 118: Subtask download_file
[2024-07-12T03:52:24.380+0000] {task_command.py:426} INFO - Running <TaskInstance: download_and_upload_to_s3.download_file scheduled__2024-07-11T00:00:00+00:00 [running]> on host 4292072e8878
[2024-07-12T03:52:24.448+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_and_upload_to_s3' AIRFLOW_CTX_TASK_ID='download_file' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T03:52:24.449+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T03:52:24.460+0000] {download_extract_dag.py:41} ERROR - Failed to download file from your_download_url: Invalid URL 'your_download_url': No scheme supplied. Perhaps you meant https://your_download_url?
[2024-07-12T03:52:24.461+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T03:52:24.461+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/download_extract_dag.py", line 33, in download_file
    response = requests.get(url)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'your_download_url': No scheme supplied. Perhaps you meant https://your_download_url?
[2024-07-12T03:52:24.471+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=download_and_upload_to_s3, task_id=download_file, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240712T035224, end_date=20240712T035224
[2024-07-12T03:52:24.487+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 118 for task download_file (Invalid URL 'your_download_url': No scheme supplied. Perhaps you meant https://your_download_url?; 513)
[2024-07-12T03:52:24.510+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T03:52:24.527+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T03:52:24.529+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
