[2024-07-12T06:55:07.589+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T06:55:07.604+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_and_invoke_lambda.invoke_lambda_unzip manual__2024-07-12T06:54:59.693643+00:00 [queued]>
[2024-07-12T06:55:07.611+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_and_invoke_lambda.invoke_lambda_unzip manual__2024-07-12T06:54:59.693643+00:00 [queued]>
[2024-07-12T06:55:07.612+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-12T06:55:07.625+0000] {taskinstance.py:2330} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_unzip> on 2024-07-12 06:54:59.693643+00:00
[2024-07-12T06:55:07.631+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1658) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T06:55:07.632+0000] {standard_task_runner.py:63} INFO - Started process 1659 to run task
[2024-07-12T06:55:07.632+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_and_invoke_lambda', 'invoke_lambda_unzip', 'manual__2024-07-12T06:54:59.693643+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/stream_upload_to_s3.py', '--cfg-path', '/tmp/tmpyt6yrlek']
[2024-07-12T06:55:07.634+0000] {standard_task_runner.py:91} INFO - Job 207: Subtask invoke_lambda_unzip
[2024-07-12T06:55:07.668+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_and_invoke_lambda.invoke_lambda_unzip manual__2024-07-12T06:54:59.693643+00:00 [running]> on host 318b387ee83d
[2024-07-12T06:55:07.748+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_and_invoke_lambda' AIRFLOW_CTX_TASK_ID='invoke_lambda_unzip' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T06:54:59.693643+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T06:54:59.693643+00:00'
[2024-07-12T06:55:07.749+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T06:55:07.759+0000] {lambda_function.py:217} INFO - Invoking AWS Lambda function: <function lambda_handler at 0x7f7150021c60> with payload: {"s3_key": "ipl_matches.zip"}
[2024-07-12T06:55:07.767+0000] {base.py:84} INFO - Using connection ID 's3-bucket-conn' for task execution.
[2024-07-12T06:55:07.768+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='s3-bucket-conn', conn_type='aws') credentials retrieved from login and password.
[2024-07-12T06:55:08.012+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T06:55:08.012+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 218, in execute
    response = self.hook.invoke_lambda(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/lambda_function.py", line 83, in invoke_lambda
    return self.conn.invoke(**trim_none_values(invoke_args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 974, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1048, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter FunctionName, value: <function lambda_handler at 0x7f7150021c60>, type: <class 'function'>, valid types: <class 'str'>
[2024-07-12T06:55:08.020+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_and_invoke_lambda, task_id=invoke_lambda_unzip, run_id=manual__2024-07-12T06:54:59.693643+00:00, execution_date=20240712T065459, start_date=20240712T065507, end_date=20240712T065508
[2024-07-12T06:55:08.043+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 207 for task invoke_lambda_unzip (Parameter validation failed:
Invalid type for parameter FunctionName, value: <function lambda_handler at 0x7f7150021c60>, type: <class 'function'>, valid types: <class 'str'>; 1659)
[2024-07-12T06:55:08.087+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T06:55:08.099+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T06:55:08.101+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
