[2024-07-14T04:52:11.339+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:52:11.364+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: glue_etl_pipeline.start_glue_crawler manual__2024-07-14T04:52:10.450357+00:00 [queued]>
[2024-07-14T04:52:11.372+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: glue_etl_pipeline.start_glue_crawler manual__2024-07-14T04:52:10.450357+00:00 [queued]>
[2024-07-14T04:52:11.372+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:52:11.385+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): start_glue_crawler> on 2024-07-14 04:52:10.450357+00:00
[2024-07-14T04:52:11.389+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=587) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T04:52:11.391+0000] {standard_task_runner.py:63} INFO - Started process 588 to run task
[2024-07-14T04:52:11.391+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'glue_etl_pipeline', 'start_glue_crawler', 'manual__2024-07-14T04:52:10.450357+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/etl_populate_database.py', '--cfg-path', '/tmp/tmpe_umdy4l']
[2024-07-14T04:52:11.392+0000] {standard_task_runner.py:91} INFO - Job 239: Subtask start_glue_crawler
[2024-07-14T04:52:11.432+0000] {task_command.py:426} INFO - Running <TaskInstance: glue_etl_pipeline.start_glue_crawler manual__2024-07-14T04:52:10.450357+00:00 [running]> on host e900ffca6a6f
[2024-07-14T04:52:11.504+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='glue_etl_pipeline' AIRFLOW_CTX_TASK_ID='start_glue_crawler' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T04:52:10.450357+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T04:52:10.450357+00:00'
[2024-07-14T04:52:11.506+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:52:11.613+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:52:11.614+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_populate_database.py", line 31, in start_crawler
    client = boto3.client('glue')
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 520, in _get_client_args
    return args_creator.get_client_args(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/args.py", line 100, in get_client_args
    final_args = self.compute_client_args(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/args.py", line 219, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/args.py", line 369, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/args.py", line 474, in _resolve_endpoint
    return endpoint_bridge.resolve(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 625, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/regions.py", line 229, in construct_endpoint
    result = self._endpoint_for_partition(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/regions.py", line 277, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
[2024-07-14T04:52:11.627+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=glue_etl_pipeline, task_id=start_glue_crawler, run_id=manual__2024-07-14T04:52:10.450357+00:00, execution_date=20240714T045210, start_date=20240714T045211, end_date=20240714T045211
[2024-07-14T04:52:11.639+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 239 for task start_glue_crawler (You must specify a region.; 588)
[2024-07-14T04:52:11.686+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T04:52:11.707+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:52:11.710+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
