[2024-07-16T07:48:00.402+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T07:48:00.421+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: glue_crawler_etl_pipeline.start_glue_job manual__2024-07-16T07:45:02.025969+00:00 [queued]>
[2024-07-16T07:48:00.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: glue_crawler_etl_pipeline.start_glue_job manual__2024-07-16T07:45:02.025969+00:00 [queued]>
[2024-07-16T07:48:00.431+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-16T07:48:00.444+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): start_glue_job> on 2024-07-16 07:45:02.025969+00:00
[2024-07-16T07:48:00.450+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2861) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-16T07:48:00.451+0000] {standard_task_runner.py:63} INFO - Started process 2862 to run task
[2024-07-16T07:48:00.451+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'glue_crawler_etl_pipeline', 'start_glue_job', 'manual__2024-07-16T07:45:02.025969+00:00', '--job-id', '294', '--raw', '--subdir', 'DAGS_FOLDER/etl_populate_database.py', '--cfg-path', '/tmp/tmpc1k17dm9']
[2024-07-16T07:48:00.452+0000] {standard_task_runner.py:91} INFO - Job 294: Subtask start_glue_job
[2024-07-16T07:48:00.491+0000] {task_command.py:426} INFO - Running <TaskInstance: glue_crawler_etl_pipeline.start_glue_job manual__2024-07-16T07:45:02.025969+00:00 [running]> on host 0ec6e6e2bd09
[2024-07-16T07:48:00.578+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='glue_crawler_etl_pipeline' AIRFLOW_CTX_TASK_ID='start_glue_job' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T07:45:02.025969+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T07:45:02.025969+00:00'
[2024-07-16T07:48:00.579+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T07:48:00.602+0000] {base.py:84} INFO - Using connection ID 's3-bucket-conn' for task execution.
[2024-07-16T07:48:00.697+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T07:48:00.698+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_populate_database.py", line 81, in start_glue_job
    response = client.start_job_run(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 974, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1048, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Role", must be one of: JobName, JobRunId, Arguments, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, NotificationProperty, WorkerType, NumberOfWorkers, ExecutionClass
[2024-07-16T07:48:00.708+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=glue_crawler_etl_pipeline, task_id=start_glue_job, run_id=manual__2024-07-16T07:45:02.025969+00:00, execution_date=20240716T074502, start_date=20240716T074800, end_date=20240716T074800
[2024-07-16T07:48:00.721+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 294 for task start_glue_job (Parameter validation failed:
Unknown parameter in input: "Role", must be one of: JobName, JobRunId, Arguments, AllocatedCapacity, Timeout, MaxCapacity, SecurityConfiguration, NotificationProperty, WorkerType, NumberOfWorkers, ExecutionClass; 2862)
[2024-07-16T07:48:00.746+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T07:48:00.765+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T07:48:00.767+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
