[2024-07-12T06:32:15.797+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T06:32:15.812+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_and_invoke_lambda.invoke_lambda_unzip manual__2024-07-12T06:32:09.926063+00:00 [queued]>
[2024-07-12T06:32:15.818+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_and_invoke_lambda.invoke_lambda_unzip manual__2024-07-12T06:32:09.926063+00:00 [queued]>
[2024-07-12T06:32:15.818+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-12T06:32:15.832+0000] {taskinstance.py:2330} INFO - Executing <Task(LambdaInvokeFunctionOperator): invoke_lambda_unzip> on 2024-07-12 06:32:09.926063+00:00
[2024-07-12T06:32:15.838+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1276) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T06:32:15.839+0000] {standard_task_runner.py:63} INFO - Started process 1277 to run task
[2024-07-12T06:32:15.839+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_and_invoke_lambda', 'invoke_lambda_unzip', 'manual__2024-07-12T06:32:09.926063+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/stream_upload_to_s3.py', '--cfg-path', '/tmp/tmpqfop9b7q']
[2024-07-12T06:32:15.840+0000] {standard_task_runner.py:91} INFO - Job 174: Subtask invoke_lambda_unzip
[2024-07-12T06:32:15.883+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_and_invoke_lambda.invoke_lambda_unzip manual__2024-07-12T06:32:09.926063+00:00 [running]> on host 318b387ee83d
[2024-07-12T06:32:15.956+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_and_invoke_lambda' AIRFLOW_CTX_TASK_ID='invoke_lambda_unzip' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T06:32:09.926063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T06:32:09.926063+00:00'
[2024-07-12T06:32:15.957+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T06:32:15.972+0000] {lambda_function.py:217} INFO - Invoking AWS Lambda function: YourLambdaFunctionName with payload: <function prepare_payload at 0x7f71531be480>
[2024-07-12T06:32:15.979+0000] {base_aws.py:587} WARNING - Unable to find AWS Connection ID 'aws_credentials', switching to empty.
[2024-07-12T06:32:15.980+0000] {base_aws.py:164} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name='your-aws-region'). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2024-07-12T06:32:16.239+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T06:32:16.240+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/lambda_function.py", line 218, in execute
    response = self.hook.invoke_lambda(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/lambda_function.py", line 83, in invoke_lambda
    return self.conn.invoke(**trim_none_values(invoke_args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 974, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1048, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Payload, value: <function prepare_payload at 0x7f71531be480>, type: <class 'function'>, valid types: <class 'bytes'>, <class 'bytearray'>, file-like object
[2024-07-12T06:32:16.248+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_and_invoke_lambda, task_id=invoke_lambda_unzip, run_id=manual__2024-07-12T06:32:09.926063+00:00, execution_date=20240712T063209, start_date=20240712T063215, end_date=20240712T063216
[2024-07-12T06:32:16.257+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 174 for task invoke_lambda_unzip (Parameter validation failed:
Invalid type for parameter Payload, value: <function prepare_payload at 0x7f71531be480>, type: <class 'function'>, valid types: <class 'bytes'>, <class 'bytearray'>, file-like object; 1277)
[2024-07-12T06:32:16.294+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T06:32:16.308+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T06:32:16.310+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
